language: python
python:
  - "2.7"


before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq



# command to install dependencies
install:
  - pip install six==1.9.0
  - pip install nose-exclude==0.2.0
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform



# command to run tests
script: 
  - nosetests -v -v --exclude-dir=backtrader/plot --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_backtrader_570bbba01e_4
  - python -m properform Push 47.88.50.110:15554 asdf_backtrader_570bbba01e_4 ./profile_backtrader_570bbba01e_4

 #2017-08-13 14:45:36 modified at 0 #2017-08-13 14:45:40 modified at 1 #2017-08-13 14:45:44 modified at 2 #2017-08-13 14:45:48 modified at 3 #2017-08-13 14:45:53 modified at 4