language: python
python:
  - "2.7"


before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq



# command to install dependencies
install:
  - pip install six==1.9.0
  - pip install nose-exclude==0.2.0
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform



# command to run tests
script: 
  - nosetests -v -v --exclude-dir=backtrader/plot --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_backtrader_74e808f9a2_1
  - python -m properform Push 47.88.50.110:15554 asdf_backtrader_74e808f9a2_1 ./profile_backtrader_74e808f9a2_1

 #2017-08-13 14:48:55 modified at 0 #2017-08-13 14:49:00 modified at 1