language: python
python:
  - "2.7"

matrix:
  allow_failures:
    python: "3.6-dev"
    python: "3.7-dev"
    python: "nightly"

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq



# command to install dependencies
install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

#  - pip install your_package
#    pip install git+https://github.com/blampe/IbPy.git

# command to run tests
script: 
  - cd tests && nosetests -v -v --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_backtrader_6247c5cbc7_4
  - python -m properform Push 47.88.50.110:15554 asdf_backtrader_6247c5cbc7_4 ./profile_backtrader_6247c5cbc7_4


 #2017-08-13 13:39:24 modified at 0 #2017-08-13 13:39:28 modified at 1 #2017-08-13 13:39:33 modified at 2 #2017-08-13 13:39:37 modified at 3 #2017-08-13 13:39:42 modified at 4