language: python
python:
  - "2.7"

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq



# command to install dependencies
install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


#  - pip install your_package

# command to run tests
script: 
  - cd tests && nosetests -v -v --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_backtrader_e017b632ac_2
  - python -m properform Push 47.88.50.110:15554 asdf_backtrader_e017b632ac_2 ./profile_backtrader_e017b632ac_2


 #2017-08-13 14:31:13 modified at 0 #2017-08-13 14:31:17 modified at 1 #2017-08-13 14:31:21 modified at 2