language: python
python:
  - "2.7"

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq



# command to install dependencies
install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


#  - pip install your_package

# command to run tests
script: 
  - cd tests && nosetests -v -v --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_backtrader_47c179e1c3_4
  - python -m properform Push 47.88.50.110:15554 asdf_backtrader_47c179e1c3_4 ./profile_backtrader_47c179e1c3_4


 #2017-08-13 14:35:38 modified at 0 #2017-08-13 14:35:42 modified at 1 #2017-08-13 14:35:46 modified at 2 #2017-08-13 14:35:50 modified at 3 #2017-08-13 14:35:55 modified at 4